project_id = "orujrrgidhlkcwbewfqc"

[functions.create-booking-checkout]
verify_jwt = false

[functions.verify-booking-payment]
verify_jwt = false

[functions.cancel-booking]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false